# Generated by Django 2.2.6 on 2021-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='formation',
            name='contenu',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
