# Generated by Django 2.2.6 on 2021-08-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_consulting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('small_desc', models.TextField(blank=True, max_length=200)),
                ('big_desc', models.TextField(blank=True, max_length=1000)),
                ('fonc', models.TextField(blank=True, max_length=10000)),
                ('other', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/')),
            ],
        ),
    ]
