# Generated by Django 2.2.6 on 2021-08-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_produit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='other',
            new_name='desc_other',
        ),
        migrations.AddField(
            model_name='produit',
            name='titre_other',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
