# Generated by Django 2.2.6 on 2021-08-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20210804_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='height',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='produit',
            name='width',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
