# Generated by Django 2.2.6 on 2021-08-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20210804_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='filter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
