# Generated by Django 2.2.6 on 2021-08-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210810_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Filters'),
        ),
    ]
