# Generated by Django 2.2.6 on 2021-08-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_produit_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='height',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='width',
        ),
    ]
