# Generated by Django 2.2.6 on 2021-08-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210812_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='necessity',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
