# Generated by Django 2.2.6 on 2021-08-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20210817_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='necessity',
            field=models.IntegerField(blank=True),
        ),
    ]
