# Generated by Django 2.2.6 on 2021-08-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='necessity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
