# Generated by Django 2.2.6 on 2021-08-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_consulting_necessity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='necessity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='necessity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
